repos:
    - repo: local
      hooks:
          - id: clean-jupyter
            name: Clean Jupyter Notebooks
            entry: ./scripts/clean_staged_notebooks.sh
            language: script
            pass_filenames: false
