repos:
    - repo: local
      hooks:
          - id: clean-jupyter
            name: Clean Jupyter Notebooks
            entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
            language: system
            files: \.ipynb$
